# This workflow will try to run it against Bro 2.4

name: Bro 2.4

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
  pull_request:
  schedule:
    - cron:  '30 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_ubuntu:
    name: Bro ${{ matrix.zeek }}
    runs-on: ubuntu-20.04
    container: broplatform/bro:2.4.1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install make
      run: apt install make

    - name: Test
      run: $GITHUB_WORKSPACE/.ci_scripts/test.sh
